spring.application.name=Maa-Sharda-Academy

server.port = ${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/maashardadb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}jdbc:mysql://localhost:3306/maashardadb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=VGhpc0lzQVN1cGVyTG9uZ1JhbmRvbVNlY3JldEtleUZvckpXVGF1dGhAMjAyNg==
jwt.expiration=3600000
